export const topics = [
  {
    id: "arrays",
    title: "Arrays",
    type: "DSA",
    level: "Beginner",
    icon: "📊",
    description: "Master traversal, searching, sorting and common array interview patterns.",
    questions: [
      "Find the largest element in an array.",
      "Find the second largest element.",
      "Reverse an array.",
      "Find duplicate elements.",
      "Move all zeroes to the end.",
      "Find the missing number.",
    ],
  },
  {
    id: "strings",
    title: "Strings",
    type: "DSA",
    level: "Beginner",
    icon: "🔤",
    description: "Practice string manipulation, frequency counting and common interview patterns.",
    questions: [
      "Check whether a string is a palindrome.",
      "Reverse a string.",
      "Find the first non-repeating character.",
      "Check whether two strings are anagrams.",
      "Compress a string.",
      "Count character frequency.",
    ],
  },
  {
    id: "linked-list",
    title: "Linked List",
    type: "DSA",
    level: "Intermediate",
    icon: "🔗",
    description: "Learn nodes, traversal, insertion, deletion and common linked-list problems.",
    questions: [
      "Reverse a linked list.",
      "Find the middle node.",
      "Detect a cycle.",
      "Merge two sorted lists.",
      "Remove duplicates.",
    ],
  },
  {
    id: "javascript",
    title: "JavaScript Basics",
    type: "JavaScript",
    level: "Beginner",
    icon: "🟨",
    description: "Revise variables, functions, arrays, objects, loops and modern JavaScript.",
    questions: [
      "Explain let, const and var.",
      "What is an arrow function?",
      "What is destructuring?",
      "Explain spread and rest operators.",
      "What is the difference between map and filter?",
      "What are template literals?",
    ],
  },
  {
    id: "react",
    title: "React Fundamentals",
    type: "React",
    level: "Intermediate",
    icon: "⚛️",
    description: "Learn JSX, components, props, state, lists and conditional rendering.",
    questions: [
      "What is JSX?",
      "What are props?",
      "What is state?",
      "Why do lists need keys?",
      "Explain conditional rendering.",
      "What is a React component?",
    ],
  },
  {
    id: "hooks",
    title: "React Hooks",
    type: "React",
    level: "Intermediate",
    icon: "🪝",
    description: "Practice useState, useEffect, useRef, useMemo, useCallback and custom hooks.",
    questions: [
      "When should you use useState?",
      "What does useEffect do?",
      "What is useRef used for?",
      "Why would you use useMemo?",
      "What is useCallback?",
      "What is a custom hook?",
    ],
  },
  {
    id: "web",
    title: "Web Fundamentals",
    type: "Frontend",
    level: "Beginner",
    icon: "🌐",
    description: "Revise HTML5, CSS3, Flexbox, Grid and responsive web design.",
    questions: [
      "What are semantic HTML tags?",
      "Explain the CSS box model.",
      "Flexbox vs Grid?",
      "What is mobile-first design?",
      "What are media queries?",
      "What is accessibility?",
    ],
  },
  {
    id: "git",
    title: "Git & GitHub",
    type: "Frontend",
    level: "Beginner",
    icon: "🐙",
    description: "Learn essential Git commands and collaboration workflows used by developers.",
    questions: [
      "What is Git?",
      "What is GitHub?",
      "What does git clone do?",
      "What is a branch?",
      "What is a pull request?",
      "What is git merge?",
    ],
  },
];

export const roadmap = [
  {
    week: "Week 1",
    title: "HTML + CSS",
    items: [
      "Semantic HTML",
      "Accessibility",
      "Box Model",
      "Flexbox",
      "Grid",
      "Responsive Design",
    ],
  },
  {
    week: "Week 2",
    title: "JavaScript",
    items: [
      "Variables",
      "Functions",
      "Arrays",
      "Objects",
      "Loops",
      "DOM Events",
    ],
  },
  {
    week: "Week 3",
    title: "Modern JavaScript",
    items: [
      "let / const",
      "Arrow Functions",
      "Destructuring",
      "Spread / Rest",
      "Promises",
      "Async / Await",
    ],
  },
  {
    week: "Week 4",
    title: "React Basics",
    items: [
      "JSX",
      "Components",
      "Props",
      "State",
      "Lists",
      "Conditional Rendering",
    ],
  },
  {
    week: "Week 5",
    title: "React Hooks",
    items: [
      "useState",
      "useEffect",
      "useRef",
      "useMemo",
      "useCallback",
      "Custom Hooks",
    ],
  },
  {
    week: "Week 6",
    title: "React Router",
    items: [
      "Routes",
      "Nested Routes",
      "Dynamic Routes",
      "Route Params",
      "Protected Routes",
      "404 Page",
    ],
  },
];

export const mockQuestions = [
  {
    id: 1,
    topic: "JavaScript",
    difficulty: "Easy",
    question: "What is the difference between let and const?",
    answer: "Both are block scoped. A let variable can be reassigned, while a const variable cannot be reassigned.",
  },
  {
    id: 2,
    topic: "React",
    difficulty: "Easy",
    question: "What is a component in React?",
    answer: "A component is a reusable piece of UI. It can receive data through props and manage changing data using state.",
  },
  {
    id: 3,
    topic: "React",
    difficulty: "Medium",
    question: "Why is useEffect used?",
    answer: "useEffect is used for side effects such as fetching data, reacting to state changes or interacting with browser APIs.",
  },
  {
    id: 4,
    topic: "CSS",
    difficulty: "Easy",
    question: "What is the CSS box model?",
    answer: "The CSS box model consists of content, padding, border and margin.",
  },
  {
    id: 5,
    topic: "JavaScript",
    difficulty: "Medium",
    question: "What is a closure?",
    answer: "A closure occurs when a function remembers and can access variables from its outer scope even after the outer function has finished.",
  },
  {
    id: 6,
    topic: "React",
    difficulty: "Medium",
    question: "What is the purpose of keys in React lists?",
    answer: "Keys help React identify which list items have changed, been added or removed.",
  },
  {
    id: 7,
    topic: "DSA",
    difficulty: "Hard",
    question: "What is the time complexity of binary search?",
    answer: "Binary search has O(log n) time complexity because the search space is divided in half at each step.",
  },
];

export const resumeTips = [
  "Keep the resume simple and easy to scan.",
  "Put your strongest technical skills near the top.",
  "Add projects with a short problem, solution and technology description.",
  "Use action words when describing what you built.",
  "Keep project descriptions honest and easy to explain.",
];

export const interviewStats = {
  total: mockQuestions.length,
};